### ISSUE TITLE
Question: Social Authentication

### ISSUE THREAD

**Issue by wassimz** [kunny/RxFirebase#11]
Hi,

Just I want to know if this library could be used with social authentication like facebook or google ?

**Comment by kunny** [comment]
If your question was 'Can I integrate social authentication using this library only?' - the answer is 'No.'

But, as [documentation](https://firebase.google.com/docs/auth/android/facebook-login) says, once you get a token from the social account provider, you can pass it to Firebase Authentication by using [RxFirebaseAuth.signInWithCredential()](https://github.com/kunny/RxFirebase/blob/rxjava2/firebase-auth/src/main/java/com/androidhuman/rxfirebase2/auth/RxFirebaseAuth.java#L64).
