### ISSUE TITLE
Update to 11.0.2 

### ISSUE THREAD

**Issue by tallnato** [kunny/RxFirebase#14]
Hi, when can you release a version with an update to version 11.0.2? 

Thanks

**Comment by kunny** [comment]
Hello, I'll release it by this weekend.

**Comment by tallnato** [comment]
Thanks great, thanks 👍

**Comment by kunny** [comment]
Just released several new versions! New features added on 11.0.0 will be followed up by #17.

**Comment by tallnato** [comment]
Thanks :)  👍
