### ISSUE TITLE
Update README.md requires jitpack.io

### ISSUE THREAD

**Issue by NateWickstrom** [kunny/RxFirebase#2]
The transitive dependency [retro-optional](https://github.com/memoizr/retro-optional) can only be found in the jitpack.io repository. That means jitpack.io is also requirment for `RxFirebase`.  It would help to add that info to your README.md, similar to the "Get It" section on [retro-optional](https://github.com/memoizr/retro-optional)
Example:
```
 repositories {
        // ...
        maven { url "https://jitpack.io" }
  }
```

**Comment by kunny** [comment]
@NateWickstrom Thanks for the issue.
I've added `transitive=false` on dependency setup guide to prevent transitive dependency, which does not require to have jitpack repository.
