### ISSUE TITLE
Update Firebase libraries to 11.4.2 

### ISSUE THREAD

**Issue by tallnato** [kunny/RxFirebase#20]
Hi,

Would it be possible to update your library to firebase 11.4.2 ? 

Thanks

**Comment by kunny** [comment]
I will do in a week.
(However, I believe it is safe to use the latest release of RxFirebase with 11.4.2 for the time being since RxFirebase does not have a compile dependency on Firebase)

**Comment by kunny** [comment]
11.4.2-compatible version has released on today. [11.4.2.0-rxjava2](https://github.com/kunny/RxFirebase/releases/tag/11.4.2.0-rxjava2)
