### ISSUE TITLE
Unable to resolve TaskResult if 'transitive=false'

### ISSUE THREAD

**Issue by ebernie** [kunny/RxFirebase#6]
This file will be unavailable com.androidhuman.rxfirebase.common.model.TaskResult. Browsed my project's dependency library and indeed, it wasn't there.

Removing 'transitive = false' seems to resolve it. What's the reason behind the flag anyway?

**Comment by kunny** [comment]
TL;DR
Adding `com.androidhuman.rxfirebase:common:{version}` will resolve your problem.

Setting up dependency was poorly documented in the readme.
I have added `transitive = true` to avoid requiring jitpack as a repository URL since `RetroOptional` depends on it.

I'll update the readme soon.

**Comment by kunny** [comment]
Update: I've choosed to remove `RetroOptional` from the project. It will be replaced with `DataValue` class which provides almost same features as `Optional` class.
(See #7 for more details)

**Comment by kunny** [comment]
Removed `RetroOptional` from usage from version 10.2.0.0.
See [wiki](https://github.com/kunny/RxFirebase/wiki) for the changes in usage.
