### ISSUE TITLE
Query does not work

### ISSUE THREAD

**Issue by ebernie** [kunny/RxFirebase#8]
Sample code:

                   final Query query = db.getReference(MESSAGES)
                            .orderByChild(MESSAGES__CONVERSATION_KEY)
                            .equalTo(defaultDialog.getId())
                            .limitToLast(1);

                    final Observable<DataSnapshot> messageObservable
                            = RxFirebaseDatabase.data(
                            query.getRef());

                    messageObservable.subscribe(dataSnapshot -> {
                        logger.logd(TAG, "RX value listener message count: " + dataSnapshot.getChildrenCount());
                    });

                    query.addListenerForSingleValueEvent(new ValueEventListener() {
                        @Override
                        public void onDataChange(DataSnapshot dataSnapshot) {
                            logger.logd(TAG, "Non-RX value listener message count: " + dataSnapshot.getChildrenCount());
                        }

                        @Override
                        public void onCancelled(DatabaseError databaseError) {

                        }
                    });

The value I get for RX and non-RX is different. The observable version is not applying any of the query criteria.

Update: after a bit of digging, I discovered that the problem lies with the fact that the listeners in [DataOnSubscribe](https://github.com/kunny/RxFirebase/blob/master/firebase-database/src/main/java/com/androidhuman/rxfirebase/database/DataOnSubscribe.java) needs to be attached to a Query object, not a DatabaseReference.

**Comment by kunny** [comment]
Thanks for the report! I'll fix this issue on the next release.

**Comment by kunny** [comment]
Added support for `Query` in version 10.2.0.0.
